image: torderdevops/env-injector:1.1.5
replicas: 2
removePodAntiAffinity: false
envFrom:
  - secretRef:
      name: stage-connect-secrets
      optional: true
environment:
  CLUSTER_NAME: aks-test-01
dnsOptions: {}
  # ndots: 3
  # single-request-reopen:
  # use-vc:
requiredNodeAffinityTerms: {}
  # - matchExpressions:
  #     - key: agentpool
  #       operator: In
  #       values:
  #         - ubuntu18
  #         - ubuntu1804
preferredNodeAffinityTerms: {}
  # - weight: 1
  #   preference:
  #     matchExpressions:
  #       - key: kubernetes.azure.com/scalesetpriority
  #         operator: DoesNotExist
tolerations: {}
  # - key: kubernetes.azure.com/scalesetpriority
  #   effect: NoSchedule
  #   operator: Equal
  #   value: spot
topologyConstraints: {}
  # - maxSkew: 1
  #   topologyKey: topology.kubernetes.io/zone
  #   whenUnsatisfiable: ScheduleAnyway
  #   nodeAffinityPolicy: Honor
  #   nodeTaintsPolicy: Honor
  #   labelSelector:
  #     matchLabels:
  #       app.kubernetes.io/name: test-app
  #   matchLabelKeys:
  #     - pod-template-hash

replicaCount: 1

service:
  port: 443

container:
  port: 8443

selectors:
  injectPrefix: env-injector.torder.com
  injectName: inject
  disableInjectLabel: disable-inject
  objectSelector:
    matchLabels:
      env-injector.torder.com/inject: "true"
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
          - kube-public
